### ISSUE TITLE
Dependency on <spawn.h>

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fujita-y/ypsilon#101]
```
The current svn version does not build on Mac OS 10.4 because there is no 
spawn.h in the system.  
Make fails with a zillion of

/bin/sh -ec 'g++ -MM -DNDEBUG 
-DSYSTEM_SHARE_PATH='"/Users/ikarus/.opt/share/ypsilon"' -
DNO_TLS src/subr_socket.cpp | sed '\''s/\(subr_socket\)\.o[ :]*/\1.o 
subr_socket.d : /g'\'' > 
subr_socket.d; [ -s subr_socket.d ] || rm -f subr_socket.d'
In file included from src/core.h:114,
                 from src/subr_socket.cpp:7:
src/sysdep.h:279:23: error: spawn.h: No such file or directory


```

Original issue reported on code.google.com by `aghul...@gmail.com` on 19 May 2009 at 7:27
